[package]
name = "buckshot"
version = "4.0.0"
authors = ["tropicbliss <tropicbliss@protonmail.com>"]
edition = "2018"
license = "MIT"
description = "A performant and capable Minecraft name sniper"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
chrono-humanize = "0.2"
console = "0.14"
dialoguer = "0.8"
lazy_static = "1.4"
native-tls = "0.2"
regex = "1.5"
reqwest = { version = "0.11", default_features = false, features = ["blocking", "cookies", "json", "multipart"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
tokio = { version = "1.12", features = ["fs", "macros", "rt-multi-thread"] }
tokio-native-tls = "0.3"
toml = "0.5"

[profile.release]
lto = true
codegen-units = 1
