[package]
name = "buckshot"
version = "2.0.0"
authors = ["tropicbliss <tropicbliss@protonmail.com>"]
edition = "2018"
license = "MIT"
homepage = "https://auth.buckshotrs.com"
repository = "https://github.com/tropicbliss/buckshot"
description = "A Minecraft username sniper written in Rust. Performant and capable."
categories = ["command-line-utilities"]
keywords = ["minecraft", "sniper", "mojang", "namesniper", "snipers"]
readme = "README.md"

[dependencies]
toml = "0.5.8"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
reqwest = { version = "0.11.4", default_features = false, features = ["json", "multipart", "stream", "rustls-tls"] }
tokio = { version = "1.8.1", features = ["fs", "rt-multi-thread", "macros"] }
chrono = "0.4.19"
bunt = "0.2.5"
argh = "0.1.5"
tokio-util = { version = "0.6.7", features = ["codec"] }
tokio-rustls = "0.22.0"
webpki-roots = "0.21.0" # Do not upgrade this
