[package]
name = "buckshot"
version = "0.1.0"
authors = ["chronicallyunfunny <test@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.8"
serde_derive = "1.0.125"
serde = "1.0.125"
futures = "0.3"
futures-io = "0.3"
async-std = "1.6"
reqwest = { version = "0.11", features = ["blocking"] }
serde_json = "1.0.64"
chrono = "0.4.19"
spin_sleep = "1.0.0"

[dependencies.async-tls]
version = "0.10"
features = ["early-data"]
