[package]
name = "buckshot"
version = "3.0.2"
authors = ["tropicbliss <tropicbliss@protonmail.com>"]
edition = "2018"
license = "MIT"
description = "A Minecraft username sniper written in Rust. Performant and capable."

[dependencies]
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", default_features = false, features = ["json", "multipart", "stream", "rustls-tls"] }
tokio = { version = "1.9", features = ["fs", "rt-multi-thread", "macros"] }
chrono = "0.4"
structopt = "0.3"
tokio-util = { version = "0.6", features = ["codec"] }
tokio-rustls = "0.22"
webpki-roots = "0.21" # do not upgrade
ansi_term = "0.12"
anyhow = "1.0"

[profile.release]
lto = true
codegen-units = 1
