[package]
name = "buckshot"
version = "0.6.0"
authors = ["chronicallyunfunny <test@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.8"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
reqwest = { version = "0.11.3", features = ["json", "multipart", "stream"] }
tokio = { version = "1.5.0", features = ["full"] }
chrono = "0.4.19"
webbrowser = "0.5.5"
bunt = "0.2.4"
native-tls = "0.2.7"
tokio-native-tls = "0.3.0"
argh = "0.1.4"
tokio-util = { version = "0.6", features = ["codec"] }
futures = "0.3"
