[package]
name = "buckshot"
version = "4.0.0"
authors = ["tropicbliss <tropicbliss@protonmail.com>"]
edition = "2018"
license = "MIT"
description = "A performant and capable Minecraft name sniper"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
console = "0.14"
dialoguer = "0.8"
native-tls = "0.2"
reqwest = { version = "0.11", features = ["blocking", "json", "multipart"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
tokio = { version = "1.11", features = ["fs", "rt-multi-thread", "macros"] }
tokio-native-tls = "0.3"
toml = "0.5"

[profile.release]
lto = true
codegen-units = 1
