# Optional fields are marked with a '#' at the start of each line (uncomment the fields by removing the '#' at the start of each line)

spread = 0 # delay between each snipe request (do not touch this unless you know what you are doing)
microsoft_auth = true
gc_snipe = false

[[account_entry]] # feel free to add multiple `account_entry` sections if you are GC sniping and want to provide multiple accounts to snipe with
email = "example@gmail.com"
password = "youaremylittlepogchamp"
#sq_ans = ["Foo", "Bar", "Baz"] # uncomment this if you are sniping with a Mojang account and have enabled security questions
#giftcode = "abc" #uncomment this to enable auto giftcode redemption

#offset = 0 # uncomment this if you want a fixed offset
#name_queue = ["Dream", "Marc"] # uncomment this to enable name queueing

#[skin] # uncomment this section if you want the sniper to upload a new skin if the snipe is successful
#skin_path = "skin.png"
#slim = false
